service: serverless-test
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: development
  region: ap-southeast-2

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  weatherApi:
    handler: src/handlers/weather.handler
    events:
      - http:
          path: get-weather/{countryCode}/{postcode}
          method: GET
          cors: true
